# Generated by Django 5.1.7 on 2025-04-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='yulKNubsterroZ8QupUgr74ProDMRNtA', editable=False, max_length=32, unique=True),
        ),
    ]
