# Generated by Django 5.1.7 on 2025-04-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='UzM9X4J4GobLCjzJ0UE7We2fJJx2WUlJ', editable=False, max_length=32, unique=True),
        ),
    ]
