# Generated by Django 5.1.7 on 2025-04-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Z4TMLws8Ig4MglGE0NLKeB2MT4XEHYJ6', editable=False, max_length=32, unique=True),
        ),
    ]
