# Generated by Django 5.1.7 on 2025-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='9uRFuYw7okN6ErDsKlxMnDSIjbvAaaJH', editable=False, max_length=32, unique=True),
        ),
    ]
